Ais\MahasiswaBundle\Entity\Mahasiswa:
 type: entity
 table: mahasiswa
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  nim:
   type: string
   length: 10
   unique: true
  nama:
   type: string
   length: 100
  daftar_id:
   type: integer
  nama_singkat:
   type: string
   length: 30
   nullable: true
  user_id:
   type: integer
   nullable: true
  email:
   type: string
   length: 100
   nullable: true
  phone:
   type: string
   length: 20
   nullable: true
  foto:
   type: string
   length: 100
   nullable: true
  is_active:
   type: boolean
   nullable: true
  is_delete:
   type: boolean
   nullable: true
