<?php

namespace Ais\MahasiswaBundle\Repository;

/**
 * MahasiswaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MahasiswaRepository extends \Doctrine\ORM\EntityRepository
{
}
